# Generated by Django 6.0.4 on 2026-04-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='menu_category',
        ),
    ]
